# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BuildRorb
                                 A QGIS plugin
 Build a RORB control vector from a catchment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-06-15
        copyright            : (C) 2023 by Tom Norman
        email                : tom@normcosystems.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Tom Norman'
__date__ = '2023-06-15'
__copyright__ = '(C) 2023 by Tom Norman'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BuildRorb class from file BuildRorb.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .build_rorb import BuildRorbPlugin
    return BuildRorbPlugin()
